package alex;

public enum ClaseLexica {
 TIPO, SEPARADOR, PYCOMA, INT, REAL, NUMNATURAL, CAP, CCIERRE, NOMBRE, REC,
 ENDOBJECT, FUN, METHOD, RETURNS, END, REFERENCIA, PAP, PCIERRE, THIS, SUPER, ENDREC,
 POINTER, OBJECT, EXTENDS, MENORIGUAL, PUNTO, APOSTROFE, MENOR, MAYOR, OUT, MAYORIGUAL,
 ALLOC, IGUAL, FREE, DISTINTO, IF, OR, ELSE, MAS, MENOS, THEN, POR, ELSIF, DIV, EOF,
 ENDIF, MOD, WHILE, AND, DO, NOT, ENDWHILE, NULL, COMA, NUMENTERO, ASIG, NUMREAL, IN, EXP, RETURN, CERO,
 CASTREAL, CASTINT
}
